/* ═══════════════════════════════════════════════════
   调度精灵 — 船舶中英文+IMO映射表
   维护说明: 新增船舶请按格式追加，空缺字段留 ""
   ═══════════════════════════════════════════════════ */

var SHIP_MAP = {
  /* ══ 已确认映射 (74艘) ══ */
  "赫尔曼湖":        { en: "LAKE HERMAN",         imo: "9953119" },
  "伊万里":          { en: "IMARI",               imo: "9567776" },
  "麒麟松":          { en: "QI LIN SONG",         imo: "9416771" },
  "爱达魔都号":      { en: "ADORA MAGIC CITY",    imo: "9871036" },
  "光武口":          { en: "GUANG WU KOU",        imo: "9990246" },
  "梦想":            { en: "DREAM",               imo: "9150913" },
  "海洋光谱号":      { en: "SPECTRUM OF THE SEAS",imo: "9778856" },
  "中谷蓬莱":        { en: "ZHONG GU PENG LAI",   imo: "9809203" },
  "新烟台":          { en: "XIN YAN TAI",         imo: "9304801" },
  "辉城":            { en: "KOTA CANTIK",         imo: "9494591" },
  "高丽阳光":        { en: "SUNNY ACACIA",        imo: "9689665" },
  "东方台北":        { en: "OOCL TAIPEI",         imo: "9477907" },
  "松云河":          { en: "SONGYUNHE",           imo: "9160700" },
  "萨姆达拉新浪先行":{ en: "SINAR SIANTAR",       imo: "9970442" },
  "奇云河":          { en: "QIYUNHE",             imo: "9228760" },
  "亚海神户":        { en: "CA KOBE",             imo: "9986714" },
  "德翔悉尼":        { en: "TS SYDNEY",           imo: "9477385" },
  "高丽达曼":        { en: "KMTC DAMMAM",         imo: "9997490" },
  "维纳斯":          { en: "CSPC VENUS",          imo: "1053303" },
  "正利艾菲":        { en: "CMA CGM EIFFEL",      imo: "9248112" },
  "正利海岛":        { en: "SHIMANAMI BAY",       imo: "9983425" },
  "东方卢森堡":      { en: "OOCL LUXEMBOURG",     imo: "9417270" },
  "国强":            { en: "KUO CHANG",           imo: "9172313" },
  "神和岛":          { en: "HARMONIZED EARTH",    imo: "9929247" },
  "亚海西贡":        { en: "CA SAIGON",           imo: "9987603" },
  "德翔大阪":        { en: "TS OSAKA",            imo: "9810111" },
  "中升拓海":        { en: "ZHONG SHENG TUO HAI", imo: "1041099" },
  "仁川协成":        { en: "CONCERTO",            imo: "9907251" },
  "高丽基隆":        { en: "KMTC KEELUNG",        imo: "9157741" },
  "东方大连":        { en: "OOCL DALIAN",         imo: "9445526" },
  "东方曼谷":        { en: "OOCL BANGKOK",        imo: "9627978" },
  "永塔":            { en: "X-PRESS ANTARES",     imo: "9875367" },
  "神颐岛":          { en: "INTEGRATIVE EARTH",   imo: "9929259" },
  "中谷营口":        { en: "ZHONG GU YING KOU",   imo: "9809239" },
  "正利青岛":        { en: "QINGDAO TOWER",       imo: "9233832" },
  "精明":            { en: "YM INTELLIGENT",      imo: "9319117" },
  "远东宏伟":        { en: "FESCO DIOMID",        imo: "9365295" },
  "正利华香":        { en: "HUA XIANG 936",       imo: "9159153" },
  "德翔槟城":        { en: "TS PENANG",           imo: "9948877" },
  "达飞里斯本":      { en: "CMA CGM LISBON",      imo: "9431800" },
  "仁川协和":        { en: "CONSISTENCE",         imo: "9865855" },
  "宝城":            { en: "KOTA PUSAKA",         imo: "9793961" },
  "东方迪尔潘":      { en: "DEAR PANEL",          imo: "9972543" },
  "新中通宁波":      { en: "PACIFIC QINGDAO",     imo: "9498688" },
  "正利战神":        { en: "CNC MARS",            imo: "9836660" },
  "东方杰作":        { en: "NORTHERN MONUMENT",   imo: "9252577" },
  "正利阿马尔菲":    { en: "AMALFI BAY",          imo: "9983451" },
  "神胜岛":          { en: "SUSTAINABLE EARTH",   imo: "9929235" },
  "长春":            { en: "WAN HAI A06",         imo: "9935129" },
  "现代地球":        { en: "HYUNDAI EARTH",       imo: "9725110" },
  "中谷济南":        { en: "ZHONG GU JI NAN",     imo: "9938872" },
  "卓明":            { en: "YM EXCELLENCE",       imo: "9496616" },
  "正利松嘉豹":      { en: "SONGA LEOPARD",       imo: "9501772" },
  "神博岛":          { en: "BLOOMING EARTH",      imo: "9950519" },
  "新中通青岛":      { en: "A ONTAKE",            imo: "9961568" },

  /* ══ 待补充映射 (出现在船期表中但尚未确认英文名/IMO) ══ */
  "东方南安普敦":    { en: "", imo: "" },
  "东方巴洛迪":      { en: "", imo: "" },
  "亚海大阪":        { en: "", imo: "" },
  "天福":            { en: "", imo: "" },  // 杂货船
  "承春":            { en: "", imo: "" },
  "新中通好运":      { en: "", imo: "" },
  "正利幸运海":      { en: "", imo: "" },
  "正利珊瑚":        { en: "", imo: "" },
  "正利邱比特":      { en: "", imo: "" },
  "泛亚广州":        { en: "", imo: "" },
  "琥珀岛":          { en: "", imo: "" },
  "神鹏岛":          { en: "", imo: "" },
  "第一汉河":        { en: "", imo: "" },
  "源明":            { en: "", imo: "" },
  "英明":            { en: "", imo: "" },
  "金顺河":          { en: "", imo: "" },
  "高丽大连":        { en: "", imo: "" },
  "高丽宁波":        { en: "", imo: "" },
  "高丽科伦坡":      { en: "", imo: "" },
  "高丽蒙巴萨":      { en: "", imo: "" },
  "高丽青岛":        { en: "", imo: "" },
  "高丽厦门":        { en: "", imo: "" },
  "远东索菲亚":      { en: "", imo: "" },
  "维纳斯":          { en: "CSPC VENUS",          imo: "1053303" }  // 杂货船，与上面维纳斯可能是同一艘
};

/* 如果不需要模块化，直接用全局变量 */
if (typeof module !== 'undefined' && module.exports) {
  module.exports = SHIP_MAP;
}
